### ISSUE TITLE
Cosmetic bug?

### ISSUE THREAD

**Issue by mdavids** [job/irrexplorer#1]
http://irrexplorer.nlnog.net/prefix/192.176.144.0/24

**Comment by htj** [comment]
I've fixed this over here:
https://github.com/NORDUnet/irrexplorer/commit/5a7cf664122d93ef9012acf620a00b478d301ebe

Job will probably merge sometime soon :-).

**Comment by job** [comment]
@htj Please send a PR!

**Comment by job** [comment]
A fix was merged in 0ff1e1860411e18b2962287151a7ab8740e327e5
