### ISSUE TITLE
query for supernet of IRR/BGP prefixes

### ISSUE THREAD

**Issue by vpallas** [job/irrexplorer#12]
Please consider supporting a query for a supernet (summary) of multiple IRR/BGP prefixes.
example: 141.36.0.0/16 -> currently "Could not find any matching prefix in IRR or BGP tables for 141.36.0.0/16"

I would like to see the combined results for all longer prefixes, in this case:
141.36.180.0/23
141.36.186.0/23

**Comment by htj** [comment]
This should be supported now. E.g.,:
http://irrexplorer.nlnog.net/search/141.36.0.0/16
