### ISSUE TITLE
Sorting of prefix column in prefix.html is dumb

### ISSUE THREAD

**Issue by job** [job/irrexplorer#13]
Currently it will sort like this:

```
1.x.x.x
10.x.x.x
2.x.x.x
etc
```

Would be good if the default sort method for that column is something that does a better job at numeric sorting :-)

**Comment by thezoggy** [comment]
while i know your using datatables, you can prob use our network parser from tablesorter without too much trouble: https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-network.js

example:
http://mottie.github.io/tablesorter/docs/example-parsers-ip-address.html

**Comment by job** [comment]
@thezoggy looks cool! I unfortunatly have zero experience with jquery/javascript :-) Waiting for someone to make a PR

**Comment by lkmhaqer** [comment]
If you don't mind a plugin, datatables seems to have this:

https://www.datatables.net/plug-ins/sorting/ip-address

**Comment by job** [comment]
Fixed by 17c3c835c91be52ca691456bd860c8bc5e5ef77c
