### ISSUE TITLE
Prefix link should be in prefix, not as

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#15]
The link to prefix info is nice, but should be on the prefix, not AS.

The as should link to either some information about the network (peeringdb?) or maybe list all prefixes for that AS.

**Comment by job** [comment]
On the prefix itself I have other plans (going to an "exact" match page with whois info). We can revisit this after I finish the "exact" functionality and see if you still think it doesnt make sense

**Comment by htj** [comment]
So I think the link should be somewhere else then. Using the AS number to link to something with the prefix is rather counter-intuitive.

**Comment by htj** [comment]
I think I am okay with the current design. I might even have started liking it :-)
Closing for now.
