### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by mdavids** [job/irrexplorer#2]
http://irrexplorer.nlnog.net/prefix/8.8.8.0/24

**Comment by job** [comment]
what is the question or remark exactly? can you attach a screenshot maybe to illustrate?

**Comment by mdavids** [comment]
2052 entries..
![screen shot 2015-05-12 at 15 08 59](https://cloud.githubusercontent.com/assets/171503/7587768/e934bba2-f8b8-11e4-9fb5-cf004a5f395d.png)
![screen shot 2015-05-12 at 15 08 35](https://cloud.githubusercontent.com/assets/171503/7587769/e951fb72-f8b8-11e4-98e8-7114e42df1df.png)

**Comment by job** [comment]
This is a feature, to put a prefix with it's more-, and less-specifics into context
