### ISSUE TITLE
Investigate the use of database for IRRexplorer

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#28]
Using py-radix requires a lot of manual work, and restricts the data model significantly.

E.g., it makes it impossible to have start+end time for certain prefix announce and do efficient queries to see what has happened for a certain prefix within a give timeframe. Such functionality can be extremely useful during dissemination of route leaks, spam origin, traffic hijacking etc.

It seems that PostgreSQL already supports the basic data type:
http://www.postgresql.org/docs/current/interactive/functions-net.html

And since 9.4 can build indexes that support efficient queries of overlaps (super/subnet):
http://michael.otacoo.com/postgresql-2/postgres-9-4-feature-highlight-gist-inet-datatype/

Further it might be worth partitioning the data on disk per database.

**Comment by htj** [comment]
So, this looks quite feasible:

CREATE TABLE routes (
    route       cidr                NOT NULL,
    asn         integer             NOT NULL,
    source      text                NOT NULL,
    CONSTRAINT valid_lengths CHECK (masklen(route) >= 8 AND masklen(route) <= 24)
);
-- constraint only works for v4

CREATE INDEX route_gist ON routes USING gist (route inet_ops);

INSERT INTO routes VALUES ('10.0.0.0/8',  'ripe');
INSERT INTO routes VALUES ('10.1.1.0/24', 'ripe');
INSERT INTO routes VALUES ('10.2.1.0/24', 'ripe');

INSERT INTO routes VALUES ('10.2.0.0/16', 'arin');

-- contained by
SELECT \* FROM routes WHERE route << '10.0.0.0/8';

-- contained by equals
SELECT \* FROM routes WHERE route <<= '10.0.0.0/8';

-- contained or covered by
SELECT \* FROM routes WHERE route && '10.2.0.0/16';

-- covered by or equals
SELECT \* FROM routes WHERE route >>= '10.1.1.0/24';

AFAICT it has all the functionality that we currently get from py-radix.

It seems to be slightly slower. A query typically takes around 7 ms with the ripe route set, but I think that is negligible.

However it becomes possible to express certain things in much easier way, like give me the routes covered by ripe_managed from a source different than RIPE. Similar it becomes possible to do start and end time for observed routes, enabling better dissemination of route leaks, IRR artefacts, etc.

Another bonus (and I think this is the biggest), is that it becomes possible to split the front-end from the back-end, so the web stuff is no longer dependant on the NRTM streamers, etc. That can just run as a background job continuously updating the database. Further, one does not have to re-load all the databases into memory when starting :-), so the web stuff, can be instantly restarted.

I know database integration is a bit last-decade, but the scheme is pretty straightforward, and the project not big enough to warrant a more fancy.architecture.

**Comment by job** [comment]
You have my blessing, go for it. Please include a ./bootstrap.sh in the repo which sets up user + db + loads schema + handles schema updates in the future

**Comment by job** [comment]
This has been fixed through your own hard work! :)
