### ISSUE TITLE
fix 'refresh' script

### ISSUE THREAD

**Issue by job** [job/irrexplorer#33]
I want the script to work like: `./refresh ripe` but it seems it will delete the entire routes table rather then just ripe.

**Comment by htj** [comment]
Possibly fixed in commit c4d5e85ac9dce7729e8321105b12c69dc30bfd26

**Comment by htj** [comment]
Proper fix in 54c1ae5987e7a90cd18ebe65012f38419af3cf81
Have even been tested. Closing this.

**Comment by job** [comment]
can you add an "all" option to refresh every entry from irrexplorer_config.yml?
