### ISSUE TITLE
Different type of warning for RFC1918 space

### ISSUE THREAD

**Issue by job** [job/irrexplorer#39]
Looking at http://irrexplorer.nlnog.net/search/10.0.0.0 

we should probably offer as advice "WTF IS THIS SHIT" instead of the current suggestion to properly register the RFC1918 space. :-)

Also maybe separate warnings for when a route-object exists versus only seeing it in BGP source.

Current rfc1918 (or we can call it 'bogon') space: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fe80::/7, 2001:db8::/32, 169.254.0.0/16 and some other blocks.

**Comment by htj** [comment]
I have added a column in the UI with rfc1918_managed for these prefixes and added a suitable warning ;-)

There is small db insert that has to be done. See commit 7c9550481ecabf13ec9e7556cc8e26d81799dc95

**Comment by htj** [comment]
Have you seen this lately?

**Comment by htj** [comment]
The wtf/minute is pretty damn high when searching through this space :-/

**Comment by htj** [comment]
Should we add Class E space as well?

**Comment by job** [comment]
Yeah, should add any bogon stuff. 

Do you want to deploy this?

**Comment by htj** [comment]
Sure. I'll take a look at it tomorrow.

**Comment by htj** [comment]
Is live:
http://irrexplorer.nlnog.net/search/192.168.0.0/16
I'll keep this ticket open, until we get RFC3927, class E and other stuff added.

**Comment by htj** [comment]
Damn, so many special things https://en.wikipedia.org/wiki/Martian_packet

Anyway, I've added RFC3927 and class E to prod. Doesn't seem anything using it, which is good (and somewhat surprising).

Might re-do how we add this later (use a single file)

**Comment by htj** [comment]
Overhauled a bit of infrastructure and added some more RFC space.
Commit 3c1a7c312ea36536902452b6af9845dd0e3a05bf

Take a look at http://irrexplorer.nlnog.net/search/10.0.0.0/16
I think AS29695 / Lysetele announces their internal table to a ring box, and not the table they would announce to an external network.
