### ISSUE TITLE
Report includes prefixes that are out of scope

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#4]
IRRExplorer seem to include prefixes that are not in scope of the requested prefix.

For instance:
http://irrexplorer.nlnog.net/prefix/193.10.68.0/24

**Comment by job** [comment]
This is a feature, not a bug! :-)

I explicitly designed it that way so you can easily get a good overview of the context of the prefix. The software searches in both BGP and IRR for the largest covering aggregate, and will then display all more specifics of that aggregate in either data source.

In a next iteration we could add a "search exact" feature or something. Pull request welcome ;-)

**Comment by htj** [comment]
OK, that makes sense. It might be nice with some text explaining that. I know the tool is still in a early phase.
