### ISSUE TITLE
Strip whitespace from user input in search box

### ISSUE THREAD

**Issue by will-h** [job/irrexplorer#41]
We should strip leading or trailing whitespace from the search box. This can occur when you copypasta and do it a bit wrong. 

Seems to work ok for AS numbers - e.g.

`http://irrexplorer.nlnog.net/search/%208330`
works

but:
`http://irrexplorer.nlnog.net/search/%205.57.80.0/20`
doesn't

**Comment by htj** [comment]
Fixed in 574670adf0fd32c75bc505457fd27be31ecdddd5 and just deployed. Thanks.
