### ISSUE TITLE
Multiple origin support

### ISSUE THREAD

**Issue by rodecker** [job/irrexplorer#42]
When multiple route objects exist for a route in the RIPE database only one origin AS is listed.

Example: 89.255.254.0/24

**Comment by job** [comment]
```
irrexplorer=# select * from routes where route = '89.255.254.0/24'::cidr;
      route      |  asn  | source_id
-----------------+-------+-----------
 89.255.254.0/24 | 59253 |        16
 89.255.254.0/24 | 60626 |        13
(2 rows)
```

Confirmed, we are only storing the last copy and not treating the (route, asn, source_id) as a the unique tuple it should be. Maybe because of the ALTDB workaround in `irrexplorer/irrupdate.py`

**Comment by htj** [comment]
The duplicate entry check in irrupdate.py includes as number, so that shouldn't be the doing this.

I had quick look around and couldn't quite find anything to explain this behaviour. I'll take a closer look sometime.

**Comment by htj** [comment]
This works after a ripe refresh, but things will break again.

Interesting that entries are right for RADB :-/
