### ISSUE TITLE
Expand AS-[0-9]+ style macro's

### ISSUE THREAD

**Issue by job** [job/irrexplorer#45]
Bug in IrrExplorer, tool doesn't work for AS-57344 (At least not the expansion part.)
In utils.py ... guess we should catch AS- or if int(data[2:]) is negative, treat it as ASmacro.

**Comment by htj** [comment]
Yeah. It is not matching on AS- first. Then tries to the as number.

Fixed in 602b32a1c16aeb025e949df341c06bf3e6c74489

Fixed search for negative or zero in 82d1df482b425a1622c9ba23f63a29a01259778a

Error messages are bad though.
