### ISSUE TITLE
Add AFRINIC to default sources list

### ISSUE THREAD

**Issue by benmaddison** [job/irrexplorer#48]

**Comment by job** [comment]
it is here already, right? https://github.com/job/irrexplorer/blob/master/irrexplorer_config.yml.dist#L2-L7

**Comment by benmaddison** [comment]
It's not in https://github.com/job/irrexplorer/blob/master/db/irr.yml though, and on http://irrexplorer.nlnog.net anything in afrinic shows up empty. e.g. http://irrexplorer.nlnog.net/search/AS-37662.

**Comment by job** [comment]
Fixed https://github.com/job/irrexplorer/commit/dc0da7b4f9228408508861298d596c40ac54db83

**Comment by job** [comment]
@benmaddison your second remark about "AS-37662" not being found has been fixed in https://github.com/job/irrexplorer/commit/ebd0061875bb1474bc474c7efed40ce96dc8df30
