### ISSUE TITLE
Confusing rpki results

### ISSUE THREAD

**Issue by erikmk** [job/irrexplorer#52]
Since i created ROA's for some of our resources the results are a bit confusing:
<img width="1090" alt="screen shot 2018-03-08 at 13 46 41" src="https://user-images.githubusercontent.com/37181435/37153766-180c6fb8-22de-11e8-93ba-de49a1cf9cbb.png">

We announce a /29 and in the roa we state it can have a max prefix of /48. Looks like a lot of the possible subnets of the /29 are also shown. Idem for ipv4

It take a lot of time to parse al this data

**Comment by job** [comment]
Hi @erikmk 

I have two comments, one is specific to the use of MaxLength, and the other is about irrexplorer.

1) I recommend not to use MaxLength, the reasons are described here https://tools.ietf.org/html/draft-yossigi-rpkimaxlen-02

2) IRRExplorer indeed makes a mess of maxlenght, do you have any better ideas? And even better, perhaps a patch to improve the readability? :-) Any contributions are very welcome!

**Comment by erikmk** [comment]
Ola @job 

Thanks for pointing out the bcp. As described in 5.1 we are currently not using the minimal roa.
i will think of an improvement! but dont expect any code :see_no_evil:

**Comment by Bryce-MW** [comment]
Hey @job, I noticed the same thing with the MaxLength attribute, I definitely agree that it should not be used if possible, but I would like to take a stab at improving how it looks in IRRExplorer. I can't appear to find where the code is that actually handles the rpki is though. Could you point me in the right direction?
