### ISSUE TITLE
ARIN (non-nonauth) IRR Seems to be Missing

### ISSUE THREAD

**Issue by TheBlueMatt** [job/irrexplorer#59]
eg http://irrexplorer.nlnog.net/search/397444 doesn't show 2620:6e:a000::/48 as listed in ARIN IRR (which it is, just not ARIN-nonauth).

**Comment by job** [comment]
what is the output you expect?

**Comment by TheBlueMatt** [comment]
2620:6e:a000::/44 should have 5 of the /48s listed in IRR as announced in BGP, but right now they all show as “ Prefix in DFZ, but no route-object with correct origin anywhere”

The /44 is also in RPKI as max-len /48 and announced correctly as such, but this displays a bit strange in the UI as “ Look like network is not announcing registered v6 prefix yet”

**Comment by TheBlueMatt** [comment]
Huh. This seems to only be an issue for IRR prefixes auto-migrated from the old ARIN email service, not IRR prefixes added via the new interface.

**Comment by TheBlueMatt** [comment]
Hmm, now all the IRR entries are missing. Seems ARIN data goes missing after being a few days old?
