### ISSUE TITLE
appconfig.cfg is missing from distribution

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#7]
Traceback (most recent call last):
  File "irrexplorer.py", line 507, in <module>
    create_app().run(host="0.0.0.0", debug=True, use_reloader=False)
  File "irrexplorer.py", line 449, in create_app
    app.config.from_pyfile('appconfig.cfg')
  File "/usr/lib/python2.7/dist-packages/flask/config.py", line 128, in from_pyfile
    with open(filename) as config_file:
IOError: [Errno 2] Unable to load configuration file (No such file or directory): '/home/htj/src/irrexplorer/appconfig.cfg'

:-(

Any chance this could be added?

I've also managed to get myself blacklisted from RADB and APNIC. I hope it it only temporary :-).

**Comment by natm** [comment]
appconfig.cfg just needs to contain a  SECRET_KEY variable, e.g...

```
 SECRET_KEY='abc123'
```

**Comment by htj** [comment]
What is that key used for?

**Comment by natm** [comment]
Flask session protection http://stackoverflow.com/questions/22463939/demystify-flask-app-secret-key

**Comment by job** [comment]
I'll leave this issue open until I write up a proper README with installation instructions

**Comment by thomas-mangin** [comment]
Should this file not be auto generated if absent on start ?

**Comment by htj** [comment]
It probably could. I'm guessing the value needs to be persistent across restarts as well.

**Comment by job** [comment]
@thomas-mangin sounds good

**Comment by job** [comment]
36ef09422bcd8116c928d58f7075c2c7c4467e41 fixes this
